# Site settings
title: Open Uptown
email: ryan@openuptown.us
description: ""
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://openuptown.us" # the base hostname & protocol for your site
twitter_username: open_uptown
github_username:  Open-Uptown

# Build settings
# markdown: kramdown
