# Site settings
title: Code, Coffee, Uptown
email: cac@uptown.codes
description: ""
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://uptown.codes" # the base hostname & protocol for your site
twitter_username: uptowncodes
github_username:  Code-and-Coffee-Uptown-Brigade

# Build settings
# markdown: kramdown
